version: "3.9"
services:
  
  marketplace:
    build:
      context: services/
      dockerfile: marketplace/Dockerfile
    environment:
      RECOMMENDATIONS_HOST: recommendations
    image: marketplace
    networks:
      - test_microservices
    ports:
      - "5000:5000"
  recommendations:
    build:
      context: services/
      dockerfile: recommendations/Dockerfile
    image: recommendations
    networks:
      - test_microservices


networks:
  test_microservices: